# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './/librarianForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_librarianForm(object):
    def setupUi(self, librarianForm):
        librarianForm.setObjectName("librarianForm")
        librarianForm.resize(934, 568)
        self.horizontalLayout = QtWidgets.QHBoxLayout(librarianForm)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(librarianForm)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.booksTab = QtWidgets.QWidget()
        self.booksTab.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.booksTab.setObjectName("booksTab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.booksTab)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.booksTable = QtWidgets.QTableWidget(self.booksTab)
        self.booksTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.booksTable.setTabKeyNavigation(False)
        self.booksTable.setProperty("showDropIndicator", True)
        self.booksTable.setDragDropOverwriteMode(False)
        self.booksTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.booksTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.booksTable.setObjectName("booksTable")
        self.booksTable.setColumnCount(7)
        self.booksTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.booksTable.setHorizontalHeaderItem(6, item)
        self.booksTable.horizontalHeader().setCascadingSectionResizes(False)
        self.booksTable.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.booksTable)
        self.widget = QtWidgets.QWidget(self.booksTab)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.addBookBtn = QtWidgets.QPushButton(self.widget_2)
        self.addBookBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBookBtn.setObjectName("addBookBtn")
        self.verticalLayout.addWidget(self.addBookBtn)
        self.delBookBtn = QtWidgets.QPushButton(self.widget_2)
        self.delBookBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delBookBtn.setObjectName("delBookBtn")
        self.verticalLayout.addWidget(self.delBookBtn)
        self.booksSaveChangesBtn = QtWidgets.QPushButton(self.widget_2)
        self.booksSaveChangesBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.booksSaveChangesBtn.setObjectName("booksSaveChangesBtn")
        self.verticalLayout.addWidget(self.booksSaveChangesBtn)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.widget_4)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.nameFilterEdit = QtWidgets.QLineEdit(self.groupBox)
        self.nameFilterEdit.setObjectName("nameFilterEdit")
        self.verticalLayout_10.addWidget(self.nameFilterEdit, 0, QtCore.Qt.AlignHCenter)
        self.genreFilterEdit = QtWidgets.QLineEdit(self.groupBox)
        self.genreFilterEdit.setObjectName("genreFilterEdit")
        self.verticalLayout_10.addWidget(self.genreFilterEdit, 0, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label)
        self.authorsList = QtWidgets.QComboBox(self.groupBox)
        self.authorsList.setEditable(True)
        self.authorsList.setObjectName("authorsList")
        self.authorsList.addItem("")
        self.authorsList.setItemText(0, "")
        self.verticalLayout_10.addWidget(self.authorsList)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_10.addWidget(self.label_2)
        self.publishersList = QtWidgets.QComboBox(self.groupBox)
        self.publishersList.setEditable(True)
        self.publishersList.setObjectName("publishersList")
        self.publishersList.addItem("")
        self.publishersList.setItemText(0, "")
        self.verticalLayout_10.addWidget(self.publishersList)
        self.searchBtn = QtWidgets.QPushButton(self.groupBox)
        self.searchBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchBtn.setObjectName("searchBtn")
        self.verticalLayout_10.addWidget(self.searchBtn)
        self.resetBtn = QtWidgets.QPushButton(self.groupBox)
        self.resetBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resetBtn.setObjectName("resetBtn")
        self.verticalLayout_10.addWidget(self.resetBtn)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.booksUpdateBtn = QtWidgets.QPushButton(self.widget_3)
        self.booksUpdateBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.booksUpdateBtn.setObjectName("booksUpdateBtn")
        self.verticalLayout_11.addWidget(self.booksUpdateBtn)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout_2.addWidget(self.widget)
        self.tabWidget.addTab(self.booksTab, "")
        self.authorsTab = QtWidgets.QWidget()
        self.authorsTab.setObjectName("authorsTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.authorsTab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.authorsTable = QtWidgets.QTableWidget(self.authorsTab)
        self.authorsTable.setObjectName("authorsTable")
        self.authorsTable.setColumnCount(3)
        self.authorsTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.authorsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.authorsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.authorsTable.setHorizontalHeaderItem(2, item)
        self.authorsTable.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_3.addWidget(self.authorsTable)
        self.widget_5 = QtWidgets.QWidget(self.authorsTab)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_9 = QtWidgets.QWidget(self.widget_5)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_4.addWidget(self.pushButton_12)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.verticalLayout_3.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.widget_5)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_10)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_12.addWidget(self.lineEdit_9, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_12.addWidget(self.pushButton_16)
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_12.addWidget(self.pushButton_19)
        self.verticalLayout_13.addWidget(self.groupBox_2)
        self.verticalLayout_3.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.widget_5)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_3.addWidget(self.widget_11)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.tabWidget.addTab(self.authorsTab, "")
        self.publishersTab = QtWidgets.QWidget()
        self.publishersTab.setObjectName("publishersTab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.publishersTab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.publishersTable = QtWidgets.QTableWidget(self.publishersTab)
        self.publishersTable.setObjectName("publishersTable")
        self.publishersTable.setColumnCount(2)
        self.publishersTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.publishersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.publishersTable.setHorizontalHeaderItem(1, item)
        self.publishersTable.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_4.addWidget(self.publishersTable)
        self.widget_12 = QtWidgets.QWidget(self.publishersTab)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_13 = QtWidgets.QWidget(self.widget_12)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_6.addWidget(self.pushButton_7)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_6.addWidget(self.pushButton_13)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_6.addWidget(self.pushButton_8)
        self.verticalLayout_5.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.widget_12)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_14)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_14.addWidget(self.lineEdit_10, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_14.addWidget(self.pushButton_17)
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_14.addWidget(self.pushButton_20)
        self.verticalLayout_15.addWidget(self.groupBox_3)
        self.verticalLayout_5.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(self.widget_12)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_5.addWidget(self.widget_15)
        self.horizontalLayout_4.addWidget(self.widget_12)
        self.tabWidget.addTab(self.publishersTab, "")
        self.ordersTab = QtWidgets.QWidget()
        self.ordersTab.setObjectName("ordersTab")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.ordersTab)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ordersTable = QtWidgets.QTableWidget(self.ordersTab)
        self.ordersTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ordersTable.setTabKeyNavigation(False)
        self.ordersTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.ordersTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ordersTable.setShowGrid(False)
        self.ordersTable.setObjectName("ordersTable")
        self.ordersTable.setColumnCount(3)
        self.ordersTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ordersTable.setHorizontalHeaderItem(2, item)
        self.ordersTable.horizontalHeader().setStretchLastSection(True)
        self.ordersTable.verticalHeader().setCascadingSectionResizes(False)
        self.ordersTable.verticalHeader().setSortIndicatorShown(True)
        self.ordersTable.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_5.addWidget(self.ordersTable)
        self.widget_16 = QtWidgets.QWidget(self.ordersTab)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_17 = QtWidgets.QWidget(self.widget_16)
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_17)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_8.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_17)
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_8.addWidget(self.pushButton_10)
        self.verticalLayout_7.addWidget(self.widget_17)
        self.widget_18 = QtWidgets.QWidget(self.widget_16)
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_18)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.ordersUpdateBtn = QtWidgets.QPushButton(self.widget_18)
        self.ordersUpdateBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ordersUpdateBtn.setObjectName("ordersUpdateBtn")
        self.verticalLayout_16.addWidget(self.ordersUpdateBtn)
        self.verticalLayout_7.addWidget(self.widget_18)
        self.widget_19 = QtWidgets.QWidget(self.widget_16)
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_7.addWidget(self.widget_19)
        self.horizontalLayout_5.addWidget(self.widget_16)
        self.tabWidget.addTab(self.ordersTab, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(librarianForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(librarianForm)

    def retranslateUi(self, librarianForm):
        _translate = QtCore.QCoreApplication.translate
        librarianForm.setWindowTitle(_translate("librarianForm", "Library: Librarian"))
        item = self.booksTable.horizontalHeaderItem(0)
        item.setText(_translate("librarianForm", "Name"))
        item = self.booksTable.horizontalHeaderItem(1)
        item.setText(_translate("librarianForm", "Genres"))
        item = self.booksTable.horizontalHeaderItem(2)
        item.setText(_translate("librarianForm", "Page count"))
        item = self.booksTable.horizontalHeaderItem(3)
        item.setText(_translate("librarianForm", "Author"))
        item = self.booksTable.horizontalHeaderItem(4)
        item.setText(_translate("librarianForm", "Publisher"))
        item = self.booksTable.horizontalHeaderItem(5)
        item.setText(_translate("librarianForm", "Count"))
        item = self.booksTable.horizontalHeaderItem(6)
        item.setText(_translate("librarianForm", "Price"))
        self.addBookBtn.setText(_translate("librarianForm", "Add"))
        self.delBookBtn.setText(_translate("librarianForm", "Delete"))
        self.booksSaveChangesBtn.setText(_translate("librarianForm", "Save"))
        self.groupBox.setTitle(_translate("librarianForm", "Filters"))
        self.nameFilterEdit.setPlaceholderText(_translate("librarianForm", "Book name"))
        self.genreFilterEdit.setPlaceholderText(_translate("librarianForm", "Genres"))
        self.label.setText(_translate("librarianForm", "Author name"))
        self.label_2.setText(_translate("librarianForm", "Publisher"))
        self.searchBtn.setText(_translate("librarianForm", "Search"))
        self.resetBtn.setText(_translate("librarianForm", "Reset"))
        self.booksUpdateBtn.setText(_translate("librarianForm", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.booksTab), _translate("librarianForm", "Books"))
        item = self.authorsTable.horizontalHeaderItem(0)
        item.setText(_translate("librarianForm", "Name"))
        item = self.authorsTable.horizontalHeaderItem(1)
        item.setText(_translate("librarianForm", "Birth date"))
        item = self.authorsTable.horizontalHeaderItem(2)
        item.setText(_translate("librarianForm", "Biography"))
        self.pushButton_5.setText(_translate("librarianForm", "Add"))
        self.pushButton_12.setText(_translate("librarianForm", "Delete"))
        self.pushButton_6.setText(_translate("librarianForm", "Save"))
        self.groupBox_2.setTitle(_translate("librarianForm", "Filter"))
        self.lineEdit_9.setPlaceholderText(_translate("librarianForm", "Author name"))
        self.pushButton_16.setText(_translate("librarianForm", "Search"))
        self.pushButton_19.setText(_translate("librarianForm", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.authorsTab), _translate("librarianForm", "Authors"))
        item = self.publishersTable.horizontalHeaderItem(0)
        item.setText(_translate("librarianForm", "Name"))
        item = self.publishersTable.horizontalHeaderItem(1)
        item.setText(_translate("librarianForm", "Creation date"))
        self.pushButton_7.setText(_translate("librarianForm", "Add"))
        self.pushButton_13.setText(_translate("librarianForm", "Delete"))
        self.pushButton_8.setText(_translate("librarianForm", "Save"))
        self.groupBox_3.setTitle(_translate("librarianForm", "Filter"))
        self.lineEdit_10.setPlaceholderText(_translate("librarianForm", "Publisher name"))
        self.pushButton_17.setText(_translate("librarianForm", "Search"))
        self.pushButton_20.setText(_translate("librarianForm", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.publishersTab), _translate("librarianForm", "Publishers"))
        item = self.ordersTable.horizontalHeaderItem(0)
        item.setText(_translate("librarianForm", "Book name"))
        item = self.ordersTable.horizontalHeaderItem(1)
        item.setText(_translate("librarianForm", "Customer login"))
        item = self.ordersTable.horizontalHeaderItem(2)
        item.setText(_translate("librarianForm", "Order date"))
        self.pushButton_9.setText(_translate("librarianForm", "Delete"))
        self.pushButton_10.setText(_translate("librarianForm", "Save"))
        self.ordersUpdateBtn.setText(_translate("librarianForm", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ordersTab), _translate("librarianForm", "Orders"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    librarianForm = QtWidgets.QWidget()
    ui = Ui_librarianForm()
    ui.setupUi(librarianForm)
    librarianForm.show()
    sys.exit(app.exec_())
