# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './/librarianForm.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_librarianForm(object):
    def setupUi(self, librarianForm):
        librarianForm.setObjectName("librarianForm")
        librarianForm.resize(728, 568)
        self.horizontalLayout = QtWidgets.QHBoxLayout(librarianForm)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(librarianForm)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tab_1.setObjectName("tab_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab_1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_1)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_2.addWidget(self.tableWidget)
        self.widget = QtWidgets.QWidget(self.tab_1)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout.addWidget(self.pushButton_11)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.widget_4)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_10.addWidget(self.lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_10.addWidget(self.lineEdit_2, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_10.addWidget(self.lineEdit_3, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_10.addWidget(self.lineEdit_4, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_14 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_10.addWidget(self.pushButton_14)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_18.setObjectName("pushButton_18")
        self.verticalLayout_10.addWidget(self.pushButton_18)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_2.addWidget(self.widget_3)
        self.horizontalLayout_2.addWidget(self.widget)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_3.addWidget(self.tableWidget_2)
        self.widget_5 = QtWidgets.QWidget(self.tab_2)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_9 = QtWidgets.QWidget(self.widget_5)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_4.addWidget(self.pushButton_12)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_9)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.verticalLayout_3.addWidget(self.widget_9)
        self.widget_10 = QtWidgets.QWidget(self.widget_5)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_10)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_12.addWidget(self.lineEdit_9, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_12.addWidget(self.pushButton_16)
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_19.setObjectName("pushButton_19")
        self.verticalLayout_12.addWidget(self.pushButton_19)
        self.verticalLayout_13.addWidget(self.groupBox_2)
        self.verticalLayout_3.addWidget(self.widget_10)
        self.widget_11 = QtWidgets.QWidget(self.widget_5)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_3.addWidget(self.widget_11)
        self.horizontalLayout_3.addWidget(self.widget_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        self.tableWidget_3.horizontalHeader().setStretchLastSection(True)
        self.horizontalLayout_4.addWidget(self.tableWidget_3)
        self.widget_12 = QtWidgets.QWidget(self.tab_3)
        self.widget_12.setObjectName("widget_12")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_13 = QtWidgets.QWidget(self.widget_12)
        self.widget_13.setObjectName("widget_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_13)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_6.addWidget(self.pushButton_7)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_6.addWidget(self.pushButton_13)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_6.addWidget(self.pushButton_8)
        self.verticalLayout_5.addWidget(self.widget_13)
        self.widget_14 = QtWidgets.QWidget(self.widget_12)
        self.widget_14.setObjectName("widget_14")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_14)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_14)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_14.addWidget(self.lineEdit_10, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_17.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_14.addWidget(self.pushButton_17)
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_20.setObjectName("pushButton_20")
        self.verticalLayout_14.addWidget(self.pushButton_20)
        self.verticalLayout_15.addWidget(self.groupBox_3)
        self.verticalLayout_5.addWidget(self.widget_14)
        self.widget_15 = QtWidgets.QWidget(self.widget_12)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_5.addWidget(self.widget_15)
        self.horizontalLayout_4.addWidget(self.widget_12)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.tab_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(3)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_4.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_4.verticalHeader().setSortIndicatorShown(True)
        self.tableWidget_4.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_5.addWidget(self.tableWidget_4)
        self.widget_16 = QtWidgets.QWidget(self.tab_4)
        self.widget_16.setObjectName("widget_16")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_16)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_17 = QtWidgets.QWidget(self.widget_16)
        self.widget_17.setObjectName("widget_17")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_17)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_17)
        self.pushButton_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_8.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_17)
        self.pushButton_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_8.addWidget(self.pushButton_10)
        self.verticalLayout_7.addWidget(self.widget_17)
        self.widget_18 = QtWidgets.QWidget(self.widget_16)
        self.widget_18.setObjectName("widget_18")
        self.verticalLayout_7.addWidget(self.widget_18)
        self.widget_19 = QtWidgets.QWidget(self.widget_16)
        self.widget_19.setObjectName("widget_19")
        self.verticalLayout_7.addWidget(self.widget_19)
        self.horizontalLayout_5.addWidget(self.widget_16)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(librarianForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(librarianForm)

    def retranslateUi(self, librarianForm):
        _translate = QtCore.QCoreApplication.translate
        librarianForm.setWindowTitle(_translate("librarianForm", "Library: Librarian"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("librarianForm", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("librarianForm", "Genres"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("librarianForm", "Page count"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("librarianForm", "Author"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("librarianForm", "Publisher"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("librarianForm", "Count"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("librarianForm", "Price"))
        self.pushButton.setText(_translate("librarianForm", "Add"))
        self.pushButton_11.setText(_translate("librarianForm", "Delete"))
        self.pushButton_2.setText(_translate("librarianForm", "Save"))
        self.groupBox.setTitle(_translate("librarianForm", "Filters"))
        self.lineEdit.setPlaceholderText(_translate("librarianForm", "Book name"))
        self.lineEdit_2.setPlaceholderText(_translate("librarianForm", "Genres via ,"))
        self.lineEdit_3.setPlaceholderText(_translate("librarianForm", "Author"))
        self.lineEdit_4.setPlaceholderText(_translate("librarianForm", "Publisher"))
        self.pushButton_14.setText(_translate("librarianForm", "Search"))
        self.pushButton_18.setText(_translate("librarianForm", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("librarianForm", "Books"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("librarianForm", "Name"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("librarianForm", "Birth date"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("librarianForm", "Biography"))
        self.pushButton_5.setText(_translate("librarianForm", "Add"))
        self.pushButton_12.setText(_translate("librarianForm", "Delete"))
        self.pushButton_6.setText(_translate("librarianForm", "Save"))
        self.groupBox_2.setTitle(_translate("librarianForm", "Filter"))
        self.lineEdit_9.setPlaceholderText(_translate("librarianForm", "Author name"))
        self.pushButton_16.setText(_translate("librarianForm", "Search"))
        self.pushButton_19.setText(_translate("librarianForm", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("librarianForm", "Authors"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("librarianForm", "Name"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("librarianForm", "Creation date"))
        self.pushButton_7.setText(_translate("librarianForm", "Add"))
        self.pushButton_13.setText(_translate("librarianForm", "Delete"))
        self.pushButton_8.setText(_translate("librarianForm", "Save"))
        self.groupBox_3.setTitle(_translate("librarianForm", "Filter"))
        self.lineEdit_10.setPlaceholderText(_translate("librarianForm", "Publisher name"))
        self.pushButton_17.setText(_translate("librarianForm", "Search"))
        self.pushButton_20.setText(_translate("librarianForm", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("librarianForm", "Publishers"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("librarianForm", "Customer name"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("librarianForm", "Book name"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("librarianForm", "Order date"))
        self.pushButton_9.setText(_translate("librarianForm", "Delete"))
        self.pushButton_10.setText(_translate("librarianForm", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("librarianForm", "Orders"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    librarianForm = QtWidgets.QWidget()
    ui = Ui_librarianForm()
    ui.setupUi(librarianForm)
    librarianForm.show()
    sys.exit(app.exec_())
